# Permalinks
permalink:           pretty

# Setup
title:               Blind3y3Design
tagline:             'Front-End Architect'
description:         'Chicago based Front-End Architect focusing on delivering premium products through UX and Front-End expertise.'
url:                 http://blind3y3design.github.io
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            1
paginate_path:       "page:num"

# Syntax Highlighting
highlighter: rouge

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Adam Sedwick
  url:               https://twitter.com/blind3y3design
  email:             asedwick@blind3y3design.com

# Custom vars
version:             4.0.0
github:              https://github.com/Blind3y3Design
medium:              https://medium.com/@blind3y3design

